<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RoAurasUpdater</AssemblyName>
    <RootNamespace>RoAuras.Updater</RootNamespace>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
</Project>
